[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow = "86b1cGBUM1RtR9wSzyQLFgwLzJTZRXiSGJr4y3hyVrJ9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/goat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
